{{- $appLabels:= (include "app.labels" .) -}}
{{- $appName:= (include "app.name" .) -}}
{{- $appPortName:= (include "app.portName" .) -}}
{{- $appSelectorLabels:= (include "app.selectorLabels" .) -}}
{{- with .Values.deployment }}
{{ $failureThreshold:= .failureThreshold }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- $appLabels | nindent 4 }}
  name: {{ $appName }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels: {{- $appSelectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $appSelectorLabels | nindent 8 }}
        {{- with .labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .containers }}
      containers:
      - image: {{ printf "%s:%s" .image.repository .image.tag }}
        imagePullPolicy: IfNotPresent
        {{- with .livenessProbe }}
        livenessProbe:
          httpGet:
            path: {{ .path }}
            port: {{ $appPortName }}
          periodSeconds: 60
        {{- end }}
        name: {{ $appName }}
        ports:
        - containerPort: {{ .containerPort }}
          name: {{ $appPortName }}
          protocol: TCP
        {{- with .readinessProbe }}
        readinessProbe:
          httpGet:
            path: {{ .path }}
            port: {{ $appPortName }}
          periodSeconds: 60
        {{- end }}
        resources: {{- toYaml .resources | nindent 10 }}
        securityContext: {{- toYaml .securityContext | nindent 10 }}
        {{- with .livenessProbe }}
        startupProbe:
          failureThreshold: {{ $failureThreshold }}
          httpGet:
            path: {{ .path }}
            port: {{ $appPortName }}
          periodSeconds: 10
        {{- end }}
      securityContext: {{- toYaml .podSecurityContext | nindent 8 }}
      {{- end }}
{{- end }}
