{{- $appLabels:= (include "app.labels" .) -}}
{{- $appName:= (include "app.name" .) -}}
{{- $appSelectorLabels:= (include "app.selectorLabels" .) -}}
{{- with .Values.ingress -}}
{{- if .enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels: {{- $appLabels | nindent 4 }}
  name: {{ $appName }}
spec:
  ingressClassName: {{ .className }}
  rules:
  {{- range .hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - backend:
          service:
            name: {{ $appName }}
            port:
              number: {{ $.Values.service.port }}
        path: {{ .path }}
        pathType: {{ .pathType }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
